# DoctrineExtensionsBundle
stof_doctrine_extensions:
    default_locale: %locale%
    orm:
        default:
            timestampable: true
            translatable:  true
            loggable:      true
            tree: true
