services:
    app.form.type.photo:
        class: AppBundle\Form\Type\ItemPhotoType
        tags:
            - { name: form.type, alias: photo }

    app.form.type.found_item:
        class: AppBundle\Form\Type\FoundItemType
        tags:
            - { name: form.type, alias: found_item }
        arguments:
            - @security.token_storage
            - @event_dispatcher

    app.form.type.lost_item:
        class: AppBundle\Form\Type\LostItemType
        tags:
            - { name: form.type, alias: lost_item }
        arguments:
            - @security.token_storage
            - @event_dispatcher

    app.form.type.area_map:
        class: AppBundle\Form\Type\AreaMapType
        tags:
            - { name: form.type, alias: area_map }
        arguments:
            - @security.token_storage

    app.form.type.item_edit:
        class: AppBundle\Form\Type\EditItemType
        tags:
            - { name: form.type, alias: item_edit }
        arguments:
            - @security.token_storage
            - @event_dispatcher

    app.form.type.feedback:
        class: AppBundle\Form\Type\FeedbackType
        tags:
            - { name: form.type, alias: feedback }

    app.form.type.statistic:
        class: AppBundle\Form\Type\StatisticType
        tags:
            - { name: form.type, alias: statistic }

    app.form.item.details:
        class: AppBundle\Form\Type\ItemDetailsType
        tags:
            - { name: form.type, alias: item_details }

    app.form.send.message:
        class: AppBundle\Form\Type\SendMessageType
        tags:
            - { name: form.type, alias: send_message }
