services:
    app.facebook_user_connected.listener:
        class: AppBundle\EventListener\FacebookUserConnectedListener
        tags:
            - { name: kernel.event_listener, event: app.facebook_user_connected, method: onUserRegistered }
        arguments:
            - @swiftmailer.mailer
            - @doctrine.orm.default_entity_manager
            - "%app.facebook_admin_user_ids%"

    app.new_item_added.listener:
        class: AppBundle\EventListener\NewItemAddedListener
        tags:
            - { name: kernel.event_listener, event: app.new_item_added, method: onItemAdded }
        arguments:
            - @swiftmailer.mailer
            - "%app.admin_emails%"

    app.add_user_edit.listener:
        class: AppBundle\EventListener\AddUserEditListener
        tags:
            - { name: kernel.event_listener, event: form.bind, method: onItemEdit }
        arguments:
            - @doctrine.orm.default_entity_manager
